[repository]  
name = "lace-border-plugin"  
authors = ["KatyaMio"]  
  
[plugins.lace-border-plugin]  
name = "lace-border-plugin"  
description = "Lace pattern border decoration for Hyprland"  
version = "1.0"  
authors = ["KatyaMio"]  
output = "liblace-border-plugin.so"  
build = [  
    "cmake -B build",  
    "cmake --build build"  
]  
since = 0
