[repository]  
name = "lace-border-plugin"  
authors = ["KatyaMio"]  
  
[[plugins]]  
name = "lace-border-plugin"  
description = "Renders lace pattern image as window border"  
version = "1.0"  
authors = ["KatyaMio"]  
output = "liblace-border-plugin.so"  
build = [  
    "cmake -B build",  
    "cmake --build build"  
]  
since = 0
